\documentclass[12pt]{article}
\usepackage{amsmath,amssymb,mathrsfs,fancyhdr,syntonly,lastpage,hyperref,enumitem,graphicx}

\hypersetup{colorlinks=true,urlcolor=black}

\topmargin      -1.5cm   % read Lamport p.163
\oddsidemargin  -0.04cm  % read Lamport p.163
\evensidemargin -0.04cm  % same as oddsidemargin but for left-hand pages
\textwidth      16.59cm
\textheight     23.94cm
\parskip         7.2pt   % sets spacing between paragraphs
\parindent         0pt   % sets leading space for paragraphs
\pagestyle{empty}        % Uncomment if don't want page numbers
\pagestyle{fancyplain}


\begin{document}
\lhead{Homework 1}
\chead{STAT 6150 - Advanced Bayesian Methods}
\rhead{Page \thepage\ of \pageref{LastPage}}

\begin{enumerate}
\item Consider the model $y\sim N(X\beta, s^2\mathrm{I})$ where $X$ is $n\times p$. Each of the following estimators corresponds to the MAP for a particular prior for $\beta$. 
  \begin{enumerate}
  \item The ridge estimator is 
  \[ \hat{\beta}_{R} = \mbox{argmin}_\beta 
\left[ (y-X\beta)^\top(y-X\beta) + \lambda \beta^\top\beta \right]. \]
State the prior distribution whose MAP corresponds to this estimator. 
State how $\lambda$ relates to this prior.
  \item The LASSO estimator is 
  \[ \hat{\beta}_{L} = \mbox{argmin}_\beta \left[ (y-X\beta)^\top(y-X\beta) + \lambda \sum_{j=1}^p |\beta_j| \right]. \]
State the prior distribution whose MAP corresponds to this estimator. 
State how $\lambda$ relates to this prior.
  \item The elastic net estimator is 
  \[ \hat{\beta}_{E} = \mbox{argmin}_\beta \left[] (y-X\beta)^\top(y-X\beta)/2 + \lambda_1 \beta'\beta + \lambda_2 \sum_{j=1}^p |\beta_j| \right]. \]
State the form of the prior distribution whose MAP corresponds to this estimator. 
State how $\lambda_1$ and $\lambda_2$ relate to this prior.
  \end{enumerate}
  
\item Consider the model 
\[
y_{i,g} \stackrel{ind}{\sim} N(\theta_g, \sigma^2),
\, g=1,\ldots,G, \, i = 1,\ldots,n_g \] 
with the following two possible hierarchical distributions for the $\theta_g$:
\[ 
\theta_g\stackrel{ind}{\sim} Ho(0,\tau^2) 
\quad \mbox{or} \quad
\theta_g \stackrel{ind}{\sim} \pi \delta_0 + (1-\pi) t_v(0,\tau^2)
\]
where $Ho(0,\tau^2)$ is the horseshoe prior described in Carvalho et al. (2009).
  \begin{enumerate}
  \item Simulate data with at least 4 groups and at least 2 observations per group. These data need not come from any of the real model proposed above (but, as described below, you will need to know the true group means...so no simulating from Cauchy distributions). 
  \item Fit both models. The choice of how to fit is up to you, but you need to provide enough details so I understand how you fit the models. Some options are JAGS, Stan, writing your own Gibbs sampler, etc. 
  \item Compare the estimated posteriors for the group specific means of the Horseshoe prior to those obtained from using the discrete mixture of a point mass at 0 and the t-distribution (you get to choose the degrees of freedom) to the true group means used in your simulation.
  \end{enumerate}
  
\end{enumerate}





\end{document}
